spring:
  application:
    name: store
server:
  port: 8081
app:
  page-size: 10
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP
Payment-Gateway: paypal
mail:
  host: https://smtp.gmail.com
  port: 5761